@extends('layouts.master')
@section('title', 'Main page')
@section('content')
    <h1 class="text-center mb-4">Posts project main page</h1>
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur commodi cum delectus, deleniti dolor dolorum, facilis fugiat harum molestias natus odio optio porro reiciendis repellendus sed? Ab adipisci aliquid, animi aperiam architecto atque autem consequuntur deserunt dignissimos dolores eveniet excepturi fugiat in ipsam, iste iusto laudantium magni maiores necessitatibus neque nobis nostrum odit placeat quaerat qui vel voluptatibus? Ab adipisci aliquid, aperiam assumenda aut commodi cupiditate deleniti dicta eligendi eos error est exercitationem facilis fuga, harum hic incidunt inventore ipsam iste itaque iure laborum maiores minima mollitia natus necessitatibus nostrum praesentium quia quisquam sapiente sequi tempora unde ut vitae voluptates.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur commodi cum delectus, deleniti dolor dolorum, facilis fugiat harum molestias natus odio optio porro reiciendis repellendus sed? Ab adipisci aliquid, animi aperiam architecto atque autem consequuntur deserunt dignissimos dolores eveniet excepturi fugiat in ipsam, iste iusto laudantium magni maiores necessitatibus neque nobis nostrum odit placeat quaerat qui vel voluptatibus? Ab adipisci aliquid, aperiam assumenda aut commodi cupiditate deleniti dicta eligendi eos error est exercitationem facilis fuga, harum hic incidunt inventore ipsam iste itaque iure laborum maiores minima mollitia natus necessitatibus nostrum praesentium quia quisquam sapiente sequi tempora unde ut vitae voluptates.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur commodi cum delectus, deleniti dolor dolorum, facilis fugiat harum molestias natus odio optio porro reiciendis repellendus sed? Ab adipisci aliquid, animi aperiam architecto atque autem consequuntur deserunt dignissimos dolores eveniet excepturi fugiat in ipsam, iste iusto laudantium magni maiores necessitatibus neque nobis nostrum odit placeat quaerat qui vel voluptatibus? Ab adipisci aliquid, aperiam assumenda aut commodi cupiditate deleniti dicta eligendi eos error est exercitationem facilis fuga, harum hic incidunt inventore ipsam iste itaque iure laborum maiores minima mollitia natus necessitatibus nostrum praesentium quia quisquam sapiente sequi tempora unde ut vitae voluptates.</p>
    </div>
@endsection
